### ISSUE TITLE
Final

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/utils#24]
Should we make BatchClient and HttpMethodsClient final?

**Comment by dbu** [comment]
a soft -1 from me. i don't think they must be final. HttpMethodsClient could be extended to add further custom HTTP verbs if wanted. if people overwrite sendRequest to hack in request manipulations instead of using a plugin, its not nice but in the end its not a huge deal either. i don't see any problems keeping them as they are.

**Comment by sagikazarmark** [comment]
OK
