### ISSUE TITLE
HTTP Methods Client implement HttpClient

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/utils#7]
Shouldn't the conventional HTTP method client implement the HttpClient interface and behave as a decorator of the underlying client?

**Comment by joelwurtz** [comment]
Yes, this might be useful, an use case that come to my mind is the usage with elasticsearch where GET requests need to set a body. 

This is not feasible in the HttpMethods actually (and that's normal), so the user will have to get HttpClient in order to use the sendRequest method in this case.

Having a decorator of the underlying client will be helpful for that.

**Comment by sagikazarmark** [comment]
Actually you can solve that by using the send method. (IIRC @dbu mentioned the same use case)
